### ISSUE TITLE
admin_review: setup.py install failed

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/geomag-imp#6]
byte-compiling /Users/mhearne/miniconda/envs/geomag/lib/python3.7/site-packages/geomag_imp/imp_io.py to imp_io.cpython-37.pyc
  File "/Users/mhearne/miniconda/envs/geomag/lib/python3.7/site-packages/geomag_imp/imp_io.py", line 79
    def write_imp_CDF(Epoch, (Latitude, Longitude, Radius), X, Y, Z, Label,
                             ^
SyntaxError: invalid syntax

**Comment by erigler-usgs** [comment]
I was unable to reproduce this problem in a fresh Py3 environment.
